export const siteConfig = {
  name: "GrygielStudio",
  person: "Jakub Grygiel",
  role: "Szybkie strony bez abonamentu",
  headline: "Strona, która jasno tłumaczy ofertę i sprawia, że klient wybiera Ciebie.",
  title: "GrygielStudio — szybkie strony bez szablonu i bez abonamentu",
  description:
    "Tworzę szybkie strony bez gotowych szablonów i bez opłat za hosting. Wizytówka, rezerwacje albo sklep — rozmawiasz bezpośrednio ze mną. Gdańsk i cała Polska.",
  email: process.env.NEXT_PUBLIC_CONTACT_EMAIL ?? "grygielstudio@gmail.com",
  phoneDisplay: "602 106 390",
  phoneHref: "tel:602106390",
  phoneE164: "+48602106390",
  location: "Gdańsk / Trójmiasto",
  area: "Cała Polska",
  github: process.env.NEXT_PUBLIC_GITHUB_URL ?? "https://github.com",
  linkedin: process.env.NEXT_PUBLIC_LINKEDIN_URL ?? "https://www.linkedin.com",
  url: process.env.NEXT_PUBLIC_SITE_URL ?? "https://grygielstudio.com",
  availability: "Przyjmuję projekty",
  keywords: [
    "strony internetowe Gdańsk",
    "strony Next.js",
    "wizytówka firmowa",
    "strona z rezerwacjami",
    "sklep internetowy",
    "GrygielStudio",
    "strony bez szablonu",
    "Trójmiasto",
  ],
};
